//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraLex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Filibuster1\\filibusterCmd.tcl")]
        public string FILIBUSTER {
            get {
                return ((string)(this["FILIBUSTER"]));
            }
            set {
                this["FILIBUSTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Filibuster1\\da\\Textprocessing\\DanLists")]
        public string EXTRALEX_LOCATION {
            get {
                return ((string)(this["EXTRALEX_LOCATION"]));
            }
            set {
                this["EXTRALEX_LOCATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Danish\\Dict\\Main")]
        public string Dictionary_MainPath {
            get {
                return ((string)(this["Dictionary_MainPath"]));
            }
            set {
                this["Dictionary_MainPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Danish\\Dict\\Name")]
        public string Dictionary_NamePath {
            get {
                return ((string)(this["Dictionary_NamePath"]));
            }
            set {
                this["Dictionary_NamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Danish\\Dict\\English")]
        public string Dictionary_EnglishPath {
            get {
                return ((string)(this["Dictionary_EnglishPath"]));
            }
            set {
                this["Dictionary_EnglishPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("danDictMain.lex")]
        public string Dictionary_Main {
            get {
                return ((string)(this["Dictionary_Main"]));
            }
            set {
                this["Dictionary_Main"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("danDictName.lex")]
        public string Dictionary_Name {
            get {
                return ((string)(this["Dictionary_Name"]));
            }
            set {
                this["Dictionary_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("danDictEnglishDANsampa.lex")]
        public string Dictionary_English {
            get {
                return ((string)(this["Dictionary_English"]));
            }
            set {
                this["Dictionary_English"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("danDictExtra.lex")]
        public string Dictionary_Extra {
            get {
                return ((string)(this["Dictionary_Extra"]));
            }
            set {
                this["Dictionary_Extra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Filibuster1\\da\\Textprocessing\\DanLists")]
        public string Dictionary_ExtraPath {
            get {
                return ((string)(this["Dictionary_ExtraPath"]));
            }
            set {
                this["Dictionary_ExtraPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("danAcronymList.txt")]
        public string Dictionary_Acronyms {
            get {
                return ((string)(this["Dictionary_Acronyms"]));
            }
            set {
                this["Dictionary_Acronyms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Filibuster1\\da\\Textprocessing\\DanLists")]
        public string Dictionary_Acronyms_Path {
            get {
                return ((string)(this["Dictionary_Acronyms_Path"]));
            }
            set {
                this["Dictionary_Acronyms_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\strawberry\\perl\\bin\\perl.exe")]
        public string PerlPath {
            get {
                return ((string)(this["PerlPath"]));
            }
            set {
                this["PerlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Filibuster1\\da\\Textprocessing\\danTextprocessing.pl")]
        public string danTextProcPath {
            get {
                return ((string)(this["danTextProcPath"]));
            }
            set {
                this["danTextProcPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Filibuster1\\da\\Textprocessing\\DanLists")]
        public string AprovedListPath {
            get {
                return ((string)(this["AprovedListPath"]));
            }
            set {
                this["AprovedListPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("whitelist.txt")]
        public string AprovedList {
            get {
                return ((string)(this["AprovedList"]));
            }
            set {
                this["AprovedList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Nota\\AudioLex\\CheckMe.txt")]
        public string CheckList {
            get {
                return ((string)(this["CheckList"]));
            }
            set {
                this["CheckList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\a_cwa lokal\\Aktuelle projekter\\Berlingske\\List\\CompleteList.txt")]
        public string CompleteList {
            get {
                return ((string)(this["CompleteList"]));
            }
            set {
                this["CompleteList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\a_cwa lokal\\Aktuelle projekter\\Berlingske\\Cached")]
        public string CachedAudio {
            get {
                return ((string)(this["CachedAudio"]));
            }
            set {
                this["CachedAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\a_cwa lokal\\Aktuelle projekter\\Talesyntese\\Nota software\\TextFilter\\TextFilter" +
            "\\TextFilterConfig\\TextFilters.xml")]
        public string TextFilter {
            get {
                return ((string)(this["TextFilter"]));
            }
            set {
                this["TextFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wish85.exe")]
        public string WishApp {
            get {
                return ((string)(this["WishApp"]));
            }
            set {
                this["WishApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FilibusterDa\\Filibuster1\\da\\Textprocessing\\DanLists\\danMultiword.lex")]
        public string DictionaryMultiWord {
            get {
                return ((string)(this["DictionaryMultiWord"]));
            }
            set {
                this["DictionaryMultiWord"] = value;
            }
        }
    }
}
